### ISSUE TITLE
Anonymous class constructor parameters should inherit nullability from parent

### ISSUE THREAD

**Issue by yborovikov** [osundblad/intellij-annotations-instrumenter-maven-plugin#14]
There's no way (i know of) to annotate anonymous class constructor parameters.

Having these inherit `@Nullable`/`@NotNull` annotations from implicitly invoked parent constructor would extend safety checks to anonymous class constructors (and prevent false positives for parent parameters annotated as `@Nullable` in case `<implicit>true</implicit>` configuration is used).

**Comment by osundblad** [comment]
Interesting idea. 

Could you give me a code example so I am sure I understand what you want?

**Comment by yborovikov** [comment]
Of course:
```
public abstract class Foo {
    protected Foo(@Nullable String name) {}
}

Foo foo = new Foo(null) {}; // anonymous class - no way to annotate constructor parameters
```
Actual behavior: `new Foo(null) {}` will throw a `NullPointerException` if instrumented with `<implicit>true</implicit>` configuration.
Expected behavior: take into account `@Nullable` annotation on `name` parameter in implicitly invoked parent `Foo(@Nullable String)` constructor (and not throw).

And - thank you for the plugin!

**Comment by osundblad** [comment]
I agree anonymous class constructors should probably not be instrumented at all. 

See if I can fix that this weekend.

**Comment by osundblad** [comment]
@yborovikov Are you using the latest version of the plugin I cannot reproduce it. And I fixed a bug regarding synthetic methods in 0.62 (if I remember correctly).

**Comment by yborovikov** [comment]
Hi @osundblad - I've attached a small maven project to reproduce the issue: [intellij-annotations-instrumenter-maven-plugin-14.zip](https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin/files/819906/intellij-annotations-instrumenter-maven-plugin-14.zip)

Unzipping it and running `mvn clean process-classes && java -cp target/classes com.example.Foo` from the project folder will fail with
> java.lang.IllegalArgumentException: Argument 0 for implicit 'NotNull' parameter of com/example/Foo$1.<init> must not be null

If one changes plugin version from `0.6.2` to `0.6.3` (or current `0.6.4-SNAPSHOT`), instrumentation goal fails with
> java.lang.NullPointerException at com.intellij.AbstractNotNullInstrumenterTask.getExcludeConfiguration(AbstractNotNullInstrumenterTask.java:107)

which seems to be a different issue.

Hope that helps.

For quick refefence - here's the contents of `src/main/java/com/example/Foo.java`:
```java
package com.example;

import org.jetbrains.annotations.Nullable;

public abstract class Foo {

    protected Foo(@Nullable String name) {}

    public static void main(String[] args) { new Foo(null) {}; }

}
```
and the relevant snippet from `pom.xml`:
```xml
    <build>
        <plugins>
            <plugin>
                <groupId>se.eris</groupId>
                <artifactId>notnull-instrumenter-maven-plugin</artifactId>
                <version>0.6.2</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <implicit>true</implicit>
                    <nullable>
                        <param>org.jetbrains.annotations.Nullable</param>
                    </nullable>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by osundblad** [comment]
Sorry missed a little implicit = true in the test ;-)

Now I have something to work on, shouldn't be that difficult so hopefully fixed this week.

**Comment by osundblad** [comment]
0.6.5 should have solved your problems, try it out as soon as you have time.

Thanks for the report!

**Comment by yborovikov** [comment]
Olle, thank you - `0.6.5` fixed the issue!
