### ISSUE TITLE
Turn off instrumentation

### ISSUE THREAD

**Issue by osundblad** [osundblad/intellij-annotations-instrumenter-maven-plugin#6]
Turn off instrumentation with an environment variable or a maven property. This is useful when you want to have the instrumentation in the main build configuration, but not in a specific maven profile, for example, when running static code analysis (eg Sonar).

**Comment by atorstling** [comment]
Aren't you done with this one? :)

**Comment by osundblad** [comment]
Jo det är jag, den är väl till och med dokumenterad i readme filen. Är inte
så duktig på admin... Hur står det till med er då? Vi borde träffas igen.
God fortsättning /Olle

**Comment by osundblad** [comment]
Solved by the parameter se.eris.notnull.instrument which can be true or false (default).
